on: 
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

name: Check test coverage
jobs:  
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x      
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: node ./scripts/index.js && npm run test
      - name: Coverage Test report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}