on: ["push", "pull_request"]
name: Test Coverage using Coveralls
jobs:
    sonarcloud:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Use NPM version 8.5.5
        run: npm install -g npm@8.5.5      
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: npx nyc --reporter lcov npm run build
      - name: Coverage Test report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
          github-token: ${{ secrets.GH_TOKEN }}