
name: Node.js CI

on: 
  workflow_dispatch:
  schedule:
  #every day at midnight
  - cron: "15 0 * * 1"

jobs:
  build:
    env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    name: Regenerate tools.json
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Regenerate
      run: npm run generate:tools
    - name: Create Pull Request with new tools.json version
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: 'chore: update tools.json'
        committer: asyncapi-bot <info@asyncapi.io>
        author: asyncapi-bot <info@asyncapi.io>
        title: 'chore: update tools.json'
        branch: update-tools/${{ github.job }}